Update README.md
Crio-Bytes/DSA pull request #35
Opened 2020-10-22 05:44 UTC by Sreejan-22

Added solution to Micro-Challenge in  ACTIVITY 1

2020-10-22 11:16 UTC, Ak-Shaw requested changes
@Sreejan-22 Kindly follow the contribution guidelines as given in CONTRIBUTING.md of the root directory of the repo. According to the contribution guidelines, you have to create an issue, before we know that you're working on something. This helps in maintaining proper workflow, also it helps us in further guiding you. Kindly use the `Update MicroByte` template for the issue.

Also, regarding your PR, kindly follow a `LearnByDoing` approach. You can use collapsible markdown as shown [here](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f). Kindly don't give away the solutions just like that, for we need the learners to get engages to task for their own good. 

I hope this gives you proper directions.

2020-10-22 19:21 UTC, Ak-Shaw requested changes
@Sreejan-22 Kindly do the needful. All else seems fine.

2020-10-22 19:21 UTC, Ak-Shaw commented on Array in Javascript/README.md
>  Can you find A way to clone an array. Create a PR and add it here as Micro-Challenge Solution
You need to remove the below statement.
`Create a PR and add it here as Micro-Challenge Solution.`

2020-10-22 19:21 UTC, Ak-Shaw commented on Array in Javascript/README.md
>  How to remove multiple elements from array in JavaScript ? Give it a try create a PR and add it here as Micro-Challenge Solution
Remove the following:
`create a PR and add it here as Micro-Challenge Solution`

2020-10-22 19:21 UTC, Ak-Shaw commented on Array in Javascript/README.md
>  Can you find more efficient solution ? Create a PR and add it here as Micro-Challenge solution
Remove the following statement:
`Create a PR and add it here as Micro-Challenge solution`

2020-10-23 10:53 UTC, Ak-Shaw approved these changes
@Sreejan-22 Nicely done! :rocket:

Kindly wait till the review process ends. Till then you are free to explore other issues or create your own!

Cheers. :beers:

2020-10-23 11:00 UTC, sudhanshutiwari264 approved these changes
Looks good to me!✨
Nice work @Sreejan-22 !

2020-10-23 11:03 UTC, merged

2020-10-23 11:05 UTC, sudhanshutiwari264 commented
@all-contributors kindly add @Nitesh-thapliyal for:

- [x] doc

2020-10-23 11:06 UTC, sudhanshutiwari264 commented
@all-contributors kindly add @Sreejan-22  for:

- [x] doc